/** @file
  Placeholder animation data — replace with gif_to_header.py output.

  This is a minimal 32x32 single-frame placeholder. To use your own animation:
  1. pip install Pillow
  2. python efi/tools/gif_to_header.py your_animation.gif -o Animation.h
  3. Copy Animation.h to efi/DioProcessEfi/
  4. Rebuild the EFI driver

  Format: BGRA32 (GOP PixelBlueGreenRedReserved8BitPerColor)
**/

#ifndef ANIMATION_H_
#define ANIMATION_H_

#include <Uefi.h>

#define ANIMATION_WIDTH       32
#define ANIMATION_HEIGHT      32
#define ANIMATION_FRAME_COUNT 2
#define ANIMATION_FRAME_SIZE  (32 * 32 * 4)

// Frame delays in milliseconds (simple 500ms blink)
STATIC CONST UINT32 AnimationDelays[] = {
    500, 500
};

// Frame 0: Violet filled square (DioProcess theme color #8b5cf6)
// BGRA: B=0xF6, G=0x5C, R=0x8B, Reserved=0x00
STATIC CONST UINT8 AnimationFrame0[ANIMATION_FRAME_SIZE] = {
    // 32x32 = 1024 pixels * 4 bytes = 4096 bytes
    // All pixels are violet: 0xF6, 0x5C, 0x8B, 0x00
#define VIOLET_PIXEL 0xF6, 0x5C, 0x8B, 0x00
#define VIOLET_ROW \
    VIOLET_PIXEL, VIOLET_PIXEL, VIOLET_PIXEL, VIOLET_PIXEL, \
    VIOLET_PIXEL, VIOLET_PIXEL, VIOLET_PIXEL, VIOLET_PIXEL, \
    VIOLET_PIXEL, VIOLET_PIXEL, VIOLET_PIXEL, VIOLET_PIXEL, \
    VIOLET_PIXEL, VIOLET_PIXEL, VIOLET_PIXEL, VIOLET_PIXEL, \
    VIOLET_PIXEL, VIOLET_PIXEL, VIOLET_PIXEL, VIOLET_PIXEL, \
    VIOLET_PIXEL, VIOLET_PIXEL, VIOLET_PIXEL, VIOLET_PIXEL, \
    VIOLET_PIXEL, VIOLET_PIXEL, VIOLET_PIXEL, VIOLET_PIXEL, \
    VIOLET_PIXEL, VIOLET_PIXEL, VIOLET_PIXEL, VIOLET_PIXEL
    VIOLET_ROW, VIOLET_ROW, VIOLET_ROW, VIOLET_ROW,
    VIOLET_ROW, VIOLET_ROW, VIOLET_ROW, VIOLET_ROW,
    VIOLET_ROW, VIOLET_ROW, VIOLET_ROW, VIOLET_ROW,
    VIOLET_ROW, VIOLET_ROW, VIOLET_ROW, VIOLET_ROW,
    VIOLET_ROW, VIOLET_ROW, VIOLET_ROW, VIOLET_ROW,
    VIOLET_ROW, VIOLET_ROW, VIOLET_ROW, VIOLET_ROW,
    VIOLET_ROW, VIOLET_ROW, VIOLET_ROW, VIOLET_ROW,
    VIOLET_ROW, VIOLET_ROW, VIOLET_ROW, VIOLET_ROW
#undef VIOLET_ROW
#undef VIOLET_PIXEL
};

// Frame 1: Black square (animation "off" frame)
STATIC CONST UINT8 AnimationFrame1[ANIMATION_FRAME_SIZE] = {
#define BLACK_PIXEL 0x00, 0x00, 0x00, 0x00
#define BLACK_ROW \
    BLACK_PIXEL, BLACK_PIXEL, BLACK_PIXEL, BLACK_PIXEL, \
    BLACK_PIXEL, BLACK_PIXEL, BLACK_PIXEL, BLACK_PIXEL, \
    BLACK_PIXEL, BLACK_PIXEL, BLACK_PIXEL, BLACK_PIXEL, \
    BLACK_PIXEL, BLACK_PIXEL, BLACK_PIXEL, BLACK_PIXEL, \
    BLACK_PIXEL, BLACK_PIXEL, BLACK_PIXEL, BLACK_PIXEL, \
    BLACK_PIXEL, BLACK_PIXEL, BLACK_PIXEL, BLACK_PIXEL, \
    BLACK_PIXEL, BLACK_PIXEL, BLACK_PIXEL, BLACK_PIXEL, \
    BLACK_PIXEL, BLACK_PIXEL, BLACK_PIXEL, BLACK_PIXEL
    BLACK_ROW, BLACK_ROW, BLACK_ROW, BLACK_ROW,
    BLACK_ROW, BLACK_ROW, BLACK_ROW, BLACK_ROW,
    BLACK_ROW, BLACK_ROW, BLACK_ROW, BLACK_ROW,
    BLACK_ROW, BLACK_ROW, BLACK_ROW, BLACK_ROW,
    BLACK_ROW, BLACK_ROW, BLACK_ROW, BLACK_ROW,
    BLACK_ROW, BLACK_ROW, BLACK_ROW, BLACK_ROW,
    BLACK_ROW, BLACK_ROW, BLACK_ROW, BLACK_ROW,
    BLACK_ROW, BLACK_ROW, BLACK_ROW, BLACK_ROW
#undef BLACK_ROW
#undef BLACK_PIXEL
};

// Array of frame pointers for indexed access
STATIC CONST UINT8* CONST AnimationFrames[] = {
    AnimationFrame0, AnimationFrame1
};

#endif // ANIMATION_H_
